executables:
  cellranger-rna: "/software/cellranger/6.0.0/bin/cellranger mkref"
genome: "/omics/groups/OE0538/internal/users/f844s/cellranger-ref/mm10/refdata-gex-mm10-2020-A/fasta/genome.fa"
annotation: "/omics/groups/OE0538/internal/users/f844s/cellranger-ref/mm10/refdata-gex-mm10-2020-A/genes/genes.gtf"
strains:
  - SPRET_EiJ
  - CAST_EiJ
additional_variant_bed_files:
  Mus_caroli: "/omics/groups/OE0538/internal/users/f844s/2022-bonemarrow/data/m.caroli/Caroli.snp.mm10.no_indels.no_chr.bed.sorted.gz"
per_strain_fasta: False
cellranger_filter_gtf: False
make_cellranger_reference: False
mode: "incorporate_snvs"  # set "maskfasta" or "incorporate_snvs"
output_directory: "results/masked_reference"
cellranger_accepted_gene_transcript_types:
  - "protein_coding" 
  - "lncRNA" 
  - "antisense" 
  - "IG_C_gene" 
  - "IG_D_gene" 
  - "IG_J_gene" 
  - "IG_LV_gene" 
  - "IG_V_gene" 
  - "IG_V_pseudogene" 
  - "IG_J_pseudogene" 
  - "IG_C_pseudogene" 
  - "TR_C_gene" 
  - "TR_D_gene" 
  - "TR_J_gene" 
  - "TR_V_gene" 
  - "TR_V_pseudogene" 
  - "TR_J_pseudogene"